Issue 2/homepage template
ThomasLdev/SnowTricks pull request #13
Opened 2021-03-05 15:35 UTC by ThomasLdev

close #2 
close #3

2021-03-06 10:03 UTC, crazymad requested changes

2021-03-06 10:03 UTC, crazymad commented on package.json
> +        "bootstrap": "^4.6.0",
boostrap and bootstrap

2021-03-06 10:03 UTC, crazymad commented on src/Controller/TrickController.php
> +     * @return Response
@param and @ not needed with PHP 7 +

2021-03-06 10:03 UTC, crazymad commented on src/Entity/Trick.php
> +    private $created_at;
camelCase

2021-03-06 10:03 UTC, crazymad commented on src/Entity/Trick.php
> +    private $updated_at;
camelCase

2021-03-12 09:43 UTC, ThomasLdev commented
corrected in next issue

2021-03-12 09:43 UTC, merged

2021-06-04 07:22 UTC, ThomasLdev commented on .env
> +DATABASE_URL="mysql://root:@127.0.0.1:3306/snow_tricks?serverVersion=mariadb-10.4.14"
ok done !

2021-06-04 07:23 UTC, ThomasLdev commented on .htaccess
> +RewriteCond %{HTTP_HOST} ^(www.)?snow-tricks.com$
yep, deleted

2021-06-04 07:23 UTC, ThomasLdev commented on package.json
> +        "bootstrap": "^4.6.0",
i kept the higher one

2021-06-04 07:23 UTC, ThomasLdev commented on src/Controller/TrickController.php
> +     * @return Response
phpstorm autocomplete ;) removed

2021-06-04 07:23 UTC, ThomasLdev commented on src/Entity/Trick.php
> +    private $created_at;
my bad, done

2021-06-04 07:23 UTC, ThomasLdev commented on src/Entity/Trick.php
> +    private $updated_at;
same

2021-06-04 07:44 UTC, ThomasLdev reviewed
all done